export const ACCOUNT_LIST = [
  {
    id: 'test1',
    name: 'Account name 1',
    masked: 'XXXXXXX',
    accNumber: '123456789',
    sortCode: '12-34-56',
    bic: '12345678',
    counterPartyName: 'John Doe',
    financialInstitutionName: 'Standard Bank',
    branchName: 'Main Branch',
    town: 'johannesburg',
    bankCountryCode: 'ZA',
    accountType: 'Current',
    addressLine1: '123 Main Street',
    currency: 'ZAR',
    countryRegion: 'South Africa',
  },
  {
    id: 'test2',
    name: 'Account name 2',
    masked: 'XXXXXXX',
    accNumber: '123456789',
    sortCode: '12-34-56',
    bic: '12345678',
    // Mock data for verified account fields
    counterPartyName: 'John Doe',
    financialInstitutionName: 'Standard Bank',
    branchName: 'Main Branch',
    town: 'johannesburg',
    bankCountryCode: 'ZA',
    accountType: 'Current',
    addressLine1: '123 Main Street',
    currency: 'ZAR',
    countryRegion: 'South Africa',
  },
  {
    id: 'test3',
    name: 'Account name 3',
    masked: 'XXXXXXX',
    accNumber: '123456789',
    sortCode: '12-34-56',
    bic: '12345678',
    // Mock data for verified account fields
    counterPartyName: 'John Doe',
    financialInstitutionName: 'Standard Bank',
    branchName: 'Main Branch',
    town: 'johannesburg',
    bankCountryCode: 'ZA',
    accountType: 'Current',
    addressLine1: '123 Main Street',
    currency: 'ZAR',
    countryRegion: 'South Africa',
  },
  {
    id: 'test4',
    name: 'Account name 4',
    masked: 'XXXXXXX',
    accNumber: '123456789',
    sortCode: '12-34-56',
    bic: '12345678',
    // Mock data for verified account fields
    counterPartyName: 'John Doe',
    financialInstitutionName: 'Standard Bank',
    branchName: 'Main Branch',
    town: 'johannesburg',
    bankCountryCode: 'ZA',
    accountType: 'Current',
    addressLine1: '123 Main Street',
    currency: 'ZAR',
    countryRegion: 'South Africa',
  },
  {
    id: 'test5',
    name: 'Account name 5',
    masked: 'XXXXXXX',
    accNumber: '123456789',
    sortCode: '12-34-56',
    bic: '12345678',
    // Mock data for verified account fields
    counterPartyName: 'John Doe',
    financialInstitutionName: 'Standard Bank',
    branchName: 'Main Branch',
    town: 'johannesburg',
    bankCountryCode: 'ZA',
    accountType: 'Current',
    addressLine1: '123 Main Street',
    currency: 'ZAR',
    countryRegion: 'South Africa',
  },
];
