export const COUNTRY_LIST = [
    { label: 'South Africa', value: 'ZA' },
    { label: 'United States', value: 'US' },
    { label: 'United Kingdom', value: 'UK' },
];

export const VERIFICATION_REQUEST_FORM_FIELDS = [
    {
        name: 'lastName' as const,
        type: 'text',
        label: 'lastName',
        placeholder: 'Enter last name or company name',
        required: true,
        gridSize: 6,
    },
    {
        name: 'idNumber' as const,
        type: 'text',
        label: 'idNumber',
        placeholder: 'Enter ID number',
        required: true,
        gridSize: 6,
    },
    {
        name: 'emailAddress' as const,
        type: 'email',
        label: 'emailAddress',
        placeholder: 'Enter email address',
        required: true,
        gridSize: 6,
    },
    {
        name: 'telephoneNumber' as const,
        type: 'text',
        label: 'telephoneNumber',
        placeholder: 'Enter telephone number',
        required: true,
        gridSize: 6,
    },
    {
        name: 'country' as const,
        type: 'select',
        label: 'country',
        placeholder: 'Select country',
        required: true,
        options: COUNTRY_LIST,
        gridSize: 6,
    },
    {
        name: 'countrySpacer' as const,
        type: 'spacer',
        gridSize: 6,
        spacer: true,
    } as any,
    {
        name: 'accountNumber' as const,
        type: 'text',
        label: 'accountNumber',
        placeholder: 'Enter account number',
        required: true,
        gridSize: 6,
    },
    {
        name: 'branchSortCode' as const,
        type: 'text',
        label: 'branchSortCode',
        placeholder: 'Enter branch or sort code',
        required: true,
        gridSize: 6,
    },
    {
        name: 'bicSwift' as const,
        type: 'text',
        label: 'bicSwift',
        placeholder: 'Enter BIC or SWIFT code',
        required: true,
        gridSize: 6,
    },
    {
        name: 'bicSpacer' as const,
        type: 'spacer',
        gridSize: 6,
        spacer: true,
    } as any,
    {
        name: 'description' as const,
        type: 'textarea',
        label: 'description',
        placeholder: 'Enter description',
        required: false,
        gridSize: 6,
        rows: 2,
    },
];

export const ACCOUNT_LIST = [
    {
        id: 'test1',
        name: 'Account name 1',
        masked: 'XXXXXXX',
        accNumber: '123456789',
        sortCode: '12-34-56',
        bic: '12345678',
        counterPartyName: 'John Doe',
        financialInstitutionName: 'Standard Bank',
        branchName: 'Main Branch',
        town: 'johannesburg',
        bankCountryCode: 'ZA',
        accountType: 'Current',
        addressLine1: '123 Main Street',
        currency: 'ZAR',
        countryRegion: 'South Africa',
    },
    {
        id: 'test2',
        name: 'Account name 2',
        masked: 'XXXXXXX',
        accNumber: '123456789',
        sortCode: '12-34-56',
        bic: '12345678',
        // Mock data for verified account fields
        counterPartyName: 'John Doe',
        financialInstitutionName: 'Standard Bank',
        branchName: 'Main Branch',
        town: 'johannesburg',
        bankCountryCode: 'ZA',
        accountType: 'Current',
        addressLine1: '123 Main Street',
        currency: 'ZAR',
        countryRegion: 'South Africa',
    },
    {
        id: 'test3',
        name: 'Account name 3',
        masked: 'XXXXXXX',
        accNumber: '123456789',
        sortCode: '12-34-56',
        bic: '12345678',
        // Mock data for verified account fields
        counterPartyName: 'John Doe',
        financialInstitutionName: 'Standard Bank',
        branchName: 'Main Branch',
        town: 'johannesburg',
        bankCountryCode: 'ZA',
        accountType: 'Current',
        addressLine1: '123 Main Street',
        currency: 'ZAR',
        countryRegion: 'South Africa',
    },
    {
        id: 'test4',
        name: 'Account name 4',
        masked: 'XXXXXXX',
        accNumber: '123456789',
        sortCode: '12-34-56',
        bic: '12345678',
        // Mock data for verified account fields
        counterPartyName: 'John Doe',
        financialInstitutionName: 'Standard Bank',
        branchName: 'Main Branch',
        town: 'johannesburg',
        bankCountryCode: 'ZA',
        accountType: 'Current',
        addressLine1: '123 Main Street',
        currency: 'ZAR',
        countryRegion: 'South Africa',
    },
    {
        id: 'test5',
        name: 'Account name 5',
        masked: 'XXXXXXX',
        accNumber: '123456789',
        sortCode: '12-34-56',
        bic: '12345678',
        // Mock data for verified account fields
        counterPartyName: 'John Doe',
        financialInstitutionName: 'Standard Bank',
        branchName: 'Main Branch',
        town: 'johannesburg',
        bankCountryCode: 'ZA',
        accountType: 'Current',
        addressLine1: '123 Main Street',
        currency: 'ZAR',
        countryRegion: 'South Africa',
    }
];
